# Generated by Django 5.1 on 2024-08-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="votes",
        ),
    ]
