# Generated by Django 5.1 on 2024-08-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_remove_answer_votes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="user",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
